### ISSUE TITLE
Ccxt Integrations

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#114]
magic8bot/src/exchange/adapters/

https://github.com/ccxt/ccxt/tree/master/js
- [ ] binance.ts
- [ ] base.ts
- [ ] gdax.ts
- [ ] index.ts
- [ ] acx.js	more standardization to the code	20 days ago
- [ ] allcoin.js	minor formatting edits	26 days ago
- [ ] anxpro.js	anxpro edit	a day ago
- [ ] anybits.js	minor formatting edits	26 days ago
- [ ] bibox.js	more standardization to the code	20 days ago
- [ ] bigone.js	bigone parseTicker previousDayClose → previousClose	8 days ago
- [ ] binance.js	certified exchanges in README.md	a day ago
- [ ] bit2c.js	minor formatting edits	26 days ago
- [ ] bitbank.js	more standardization to the code	20 days ago
- [ ] bitbay.js	bitbay changed their jurisdiction to Malta	2 months ago
- [ ] bitfinex.js	certified exchanges in README.md	a day ago
- [ ] bitfinex2.js	certified exchanges in README.md	a day ago
- [ ] bitflyer.js	more standardization to the code	20 days ago
- [ ] bithumb.js	minor formatting edits	26 days ago
- [ ] bitkk.js	added bitkk fix #2487	4 months ago
- [ ] bitlish.js	resync	4 months ago
- [ ] bitmarket.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] bitmex.js	a better typecheck for a defined/undefined market everywhere	20 days ago
- [ ] bitsane.js	more standardization to the code	20 days ago
- [ ] bitso.js	bitso unified fetchOrderTrades signature	11 days ago
- [ ] bitstamp.js	Fix bitstamp fee in case no transactions.	9 days ago
- [ ] bitstamp1.js	more standardization to the code	20 days ago
- [ ] bittrex.js	certified exchanges in README.md	a day ago
- [ ] bitz.js	remove bitz warning merge #3413, fix #3271	8 days ago
- [ ] bl3p.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] bleutrade.js	minor edits + Certification.md added	18 hours ago
- [ ] braziliex.js	a better typecheck for a defined/undefined market everywhere	20 days ago
- [ ] btcalpha.js	btcalpha error handling fix #1742	13 days ago
- [ ] btcbox.js	minor formatting edits	26 days ago
- [ ] btcchina.js	minor formatting edits	26 days ago
- [ ] btcexchange.js	minor formatting edits	26 days ago
- [ ] btcmarkets.js	added ids to btcmarkets cancelOrder signature for unification	4 days ago
- [ ] btctradeim.js	btctradeim describe options['quoteIds'] in PHP fix #3343	15 days ago
- [ ] btctradeua.js	minor formatting edits	26 days ago
- [ ] btcturk.js	minor formatting edits	26 days ago
- [ ] btcx.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] bxinth.js	minor formatting edits	26 days ago
- [ ] ccex.js	ccex VIT → VitalCoin fix #2987 https://c-cex.com/?id=info	2 months ago
- [ ] cex.js	more standardization to the code	20 days ago
- [ ] chbtc.js	minor formatting edits	26 days ago
- [ ] chilebit.js	minor formatting edits	26 days ago
- [ ] cobinhood.js	cobinhood restored fetchDepositAddress and createDepositAddress refix #…	4 days ago
- [ ] coinbase.js	minor formatting edits	26 days ago
- [ ] coinbasepro.js	coinbase pro logo	a month ago
- [ ] coincheck.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] coinegg.js	allow use all regions for coinegg	a month ago
- [ ] coinex.js	coinex fetchBalance endpoint changed "balance" → "balance/info" fix #…	3 days ago
- [ ] coinexchange.js	coinexchange OC → occnetwork fix #3350	14 days ago
- [ ] coinfalcon.js	coinfalcon private api / transpiler fix #3437	6 days ago
- [ ] coinfloor.js	coinfloor parseDate → parse8601	2 days ago
- [ ] coingi.js	resync	4 months ago
- [ ] coinmarketcap.js	a better typecheck for a defined/undefined market everywhere	20 days ago
- [ ] coinmate.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] coinnest.js	more standardization to the code	20 days ago
- [ ] coinone.js	Merge remote-tracking branch 'ccxt/master'	8 days ago
- [ ] coinsecure.js	minor formatting edits	26 days ago
- [ ] coinspot.js	minor formatting edits	26 days ago
- [ ] cointiger.js	minor simplifications in cointiger sign()	4 days ago
- [ ] coolcoin.js	minor formatting edits	26 days ago
- [ ] crypton.js	more standardization to the code	20 days ago
- [ ] cryptopia.js	more fixes to cryptopia #3421	8 days ago
- [ ] deribit.js	minor formatting edits	26 days ago
- [ ] dsx.js	minor formatting edits	26 days ago
- [ ] ethfinex.js	minor edits + Certification.md added	18 hours ago
- [ ] exmo.js	minor typos	20 days ago
- [ ] exx.js	exx error handling fix #3355	11 days ago
- [ ] fcoin.js	fcoin fetchOHLCV seq vs timestamp fix #3440	5 days ago
- [ ] flowbtc.js	minor formatting edits	26 days ago
- [ ] foxbit.js	minor formatting edits	26 days ago
- [ ] fybse.js	minor formatting edits	26 days ago
- [ ] fybsg.js	minor formatting edits	26 days ago
- [ ] gatecoin.js	minor formatting edits	26 days ago
- [ ] gateio.js	Fix gate.io feeRate	9 days ago
- [ ] gdax.js	more standardization to the code	20 days ago
- [ ] gemini.js	removed unnecessary double-filtering	8 days ago
- [ ] getbtc.js	updated gemini, getbtc, kuna, xbtce metainfo	5 months ago
- [ ] hadax.js	hadax FAIR → FairGame refix #3364	13 days ago
- [ ] hitbtc.js	Declare hitbtc fetchOrderTrades.	10 days ago
- [ ] hitbtc2.js	hitbtc2 fetchClosedOrders return canceled as well	8 days ago
- [ ] huobi.js	minor formatting edits	26 days ago
- [ ] huobicny.js	huobicny linting	6 months ago
- [ ] huobipro.js	huobipro fetchOrdersByStates does not require a symbol fix #3429	7 days ago
- [ ] ice3x.js	more standardization to the code	20 days ago
- [ ] independentreserve.js	independentreserve fix #2567	8 days ago
- [ ] indodax.js	more standardization to the code	20 days ago
- [ ] itbit.js	minor formatting edits	26 days ago
- [ ] jubi.js	minor formatting edits	26 days ago
- [ ] kraken.js	certified exchanges in README.md	a day ago
- [ ] kucoin.js	Fix kucoin order status.	15 days ago
- [ ] kuna.js	more standardization to the code	20 days ago
- [ ] lakebtc.js	lakebtc sign() refix	12 days ago
- [ ] lbank.js	space	9 days ago
- [ ] liqui.js	minor edits in liqui	10 days ago
- [ ] livecoin.js	minor edits	14 days ago
- [ ] luno.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] lykke.js	a better typecheck for a defined/undefined market everywhere	20 days ago
- [ ] mercado.js	more standardization to the code	20 days ago
- [ ] mixcoins.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] negociecoins.js	a better typecheck for a defined/undefined market everywhere	20 days ago
- [ ] nova.js	minor formatting edits	26 days ago
- [ ] okcoincny.js	minor formatting edits	26 days ago
- [ ] okcoinusd.js	minor revert	15 hours ago
- [ ] okex.js	okex: arg name fix in fetchTickers	6 days ago
- [ ] paymium.js	paymium refix, transpiler fix for excessive linespace, cancelOrder ed…	2 months ago
- [ ] poloniex.js	poloniex fix #3411	9 days ago
- [ ] qryptos.js	qryptos fetchTrades since milliseconds vs seconds fix	9 days ago
- [ ] quadrigacx.js	minor formatting edits	26 days ago
- [ ] quoinex.js	quoinex, bitmex no hardcoded fees #2447	4 months ago
- [ ] rightbtc.js	RightBTC: Rewrite XRB to NANO.	2 days ago
- [ ] southxchange.js	minor formatting edits	26 days ago
- [ ] surbitcoin.js	minor formatting edits	26 days ago
- [ ] theocean.js	createOrder makerOrTaker param	a day ago
- [ ] therock.js	minor formatting edits	26 days ago
- [ ] tidebit.js	more standardization to the code	20 days ago
- [ ] tidex.js	minor formatting edits	26 days ago
- [ ] urdubit.js	minor formatting edits	26 days ago
- [ ] vaultoro.js	minor formatting edits	26 days ago
- [ ] vbtc.js	minor formatting edits	26 days ago
- [ ] virwox.js	Use safeFloat in general to avoid getting errors when API fields change	3 months ago
- [ ] wex.js	minor formatting edits	26 days ago
- [ ] xbtce.js	xbtce public api is now available fix #3000	11 days ago
- [ ] yobit.js	minor transpiler fix for yobit #3372	14 days ago
- [ ] yunbi.js	minor formatting edits	26 days ago
- [ ] zaif.js	zaif quick patch for fetchTrades / emulated fetchOHLCV / empty trades…	14 days ago
- [ ] zb.js
