### ISSUE TITLE
Refactor Strategies

### ISSUE THREAD

**Issue by notVitaliy** [magic8bot/magic8bot#3]
The idea is to remove the dependence on the `s` var. It's currently abstracted away with the `StrategyService` but that's not ideal.

Each strategy should expose its options via a static property on the class. Something like this.
```typescript
interface Options {
  default: any
  type: 'int' | 'bool' | 'string'
}

class FakeStrategy {
  static: Record<string, Option> = {
    opt1: { default: 0, type: 'int' },
    opt2: { default: false, type: 'bool' },
  }
}
```
So then the config can be analysed at runtime and these options can be exposed to the `Core`, which will then relay that info to the interface (webui, cli, etc...)

- [ ] bollinger
- [ ] cci_srsi
- [ ] crossover_vwap
- [ ] dema
- [ ] ehlers_ft
- [ ] ehlers_mama
- [ ] ehlers_trend
- [ ] forex_analytics
- [ ] ichimoku
- [ ] ichimoku_Score
- [ ] kc
- [x] macd
- [ ] momentum
- [ ] neural
- [ ] noop
- [ ] rsi
- [ ] sar
- [ ] speed
- [ ] srsi_macd
- [ ] stddev
- [ ] ta_ema
- [ ] ta_macd
- [ ] ta_macd_ext
- [ ] ta_ppo
- [ ] ta_srsi_bollinger
- [ ] ta_stoch_bollinger
- [ ] ta_trix
- [ ] ta_ultosc
- [ ] ti_bollinger
- [ ] ti_hma
- [ ] ti_stoch
- [ ] ti_stoch_bollinger
- [ ] trend_bollinger
- [ ] trend_ema
- [ ] trendline
- [ ] trust_distrust
- [ ] wavetrend
