### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by notVitaliy** [magic8bot/magic8bot#7]
### Dependencies
_indentation means the proceeding dependencies are sub-dependencies_

- [x] For each exchange, create a new `Engine`
  - [x] Init the `ExchangeService`
  - [x] For each currency pair
    - [x] Init the `TradeStore`
    - [x] Init the `TradeService`
    - [ ] For each strategy
      - [ ] Init the `StrategyService`
        - [ ] Init the `OrderStore`
        - [ ] Init the `PeriodStore`
        - [ ] Init the `WalletStore`
        - [ ] Init the `WalletService`
        - [ ] Init the `OrderService`

### Service

A class whose primary functions are to interface with an external data source or process data for consumption by a store or other service. These classes should never hold an internal dataset . or with the exception of its configuration.

e.g. The `TradeService` will keep track of which exchange it belongs to, which selectors are "active" and what the most recent marker/cursor for each selector. It will never hold any trade data.

### Store
A class whose primary functions pertains to reading data from the database, keeping a copy of its dataset in memory, and writing new data to the database.

e.g. The `TradeStore` saves and loads trade data as well as storing it for in-memory caching purposes but it will never hold information about _how_ to get new trade date from an exchange only from its database/collection.

### Functions

- [x] Can backfill trade data
  - [x] Can scan backward
  - [x] Can scan forward
- [ ] Can sync wallet data
- [ ] Can poll exchange for new trade data
- [ ] Can pipe trade data to `StrategyService`
- [ ] Can execute a new order
- [ ] Can update an open order
- [ ] Can cancel an open order
